# Generated by Django 2.1.2 on 2019-04-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('brand_name', models.CharField(max_length=20)),
                ('show_date', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('is_show', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('create_date', models.DateField()),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'shop',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Shop'),
        ),
    ]
